package helloApp;


/**
* helloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from helloApp.idl
* vendredi 3 mai 2019 11 h 41 CEST
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
