package chat_corba;

/**
* chat_corba/ChatServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat_corba.idl
* vendredi 3 mai 2019 13 h 51 CEST
*/

public final class ChatServerHolder implements org.omg.CORBA.portable.Streamable
{
  public chat_corba.ChatServer value = null;

  public ChatServerHolder ()
  {
  }

  public ChatServerHolder (chat_corba.ChatServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat_corba.ChatServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat_corba.ChatServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat_corba.ChatServerHelper.type ();
  }

}
