package chat_corba;


/**
* chat_corba/ChatClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat_corba.idl
* vendredi 3 mai 2019 13 h 51 CEST
*/

public interface ChatClientOperations 
{
  String getUserName ();
  void addMSG (String msg);
  void updateConnectedUsers (String[] names);
} // interface ChatClientOperations
