package chat_corba;


/**
* chat_corba/ChatServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat_corba.idl
* vendredi 3 mai 2019 13 h 51 CEST
*/

public interface ChatServer extends ChatServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ChatServer
