package chat_corba;


/**
* chat_corba/ChatServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat_corba.idl
* vendredi 3 mai 2019 13 h 51 CEST
*/

public interface ChatServerOperations 
{
  void register (chat_corba.ChatClient c);
  void unRegister (chat_corba.ChatClient c);
  void sendToAll (String msg, chat_corba.ChatClient from);
} // interface ChatServerOperations
